items:
  radiant:
    gg_booster:
      title: "&CTEST"
      modifier: booster-1
    level_booster:
      title: "&CTEST 2"
      modifier: booster-2
    event_booster:
      title: "&CTEST 3"
      modifier: booster-3
  brilliant:
    gg_booster:
      title: "&CTEST"
      modifier: booster-1
    level_booster:
      title: "&CTEST 2"
      modifier: booster-2
    event_booster:
      title: "&CTEST 3"
      modifier: booster-3
  legendary:
    gg_booster:
      title: "&CTEST"
      modifier: booster-1
    level_booster:
      title: "&CTEST 2"
      modifier: booster-2
    event_booster:
      title: "&CTEST 3"
      modifier: booster-3
data:
  radiant:
    total: 0
    holder: ""
    item: gg_booster
  brilliant:
    total: 0
    holder: ""
    item: gg_booster
  legendary:
    total: 0
    holder: ""
    item: gg_booster