items:
  radiant:
    '1':
      title: "&CTEST"
      modifier: booster-1
    '2':
      title: "&CTEST 2"
    '3':
      title: "&CTEST 3"
    '4':
      title: "&CTEST 4"
  brilliant:
    '1':
      title: "&4TEST"
    '2':
      title: "&4TEST 2"
    '3':
      title: "&4TEST 3"
    '4':
      title: "&4TEST 4"
  legendary:
    '1':
      title: "&5TEST"
    '2':
      title: "&5TEST 2"
    '3':
      title: "&5TEST 3"
    '4':
      title: "&5TEST 4"
data:
  radiant:
    total: 0
    holder: ""
    modifier: ""
  brilliant:
    total: 0
    holder: ""
    modifier: ""
  legendary:
    total: 0
    holder: ""
    modifier: ""