items:
  test-1:
    title: "&cTest"
    description: "This is a test 1!"
  test-2:
    title: "&cTest"
    description: "This is a test 2!"
  test-3:
    title: "&cTest"
    description: "This is a test 3!"
  test-4:
    title: "&cTest"
    description: "This is a test 4!"