clans:
  # XP Needed to level up
  '1':
    xp-needed: 1000
  '2':
    xp-needed: 10000
  '3':
    xp-needed: 100000
  '4':
    xp-needed: 1000000
  '5':
    xp-needed: 10000000
  '6':
    xp-needed: 20000000
  '7':
    xp-needed: 30000000
  '8':
    xp-needed: 40000000
  '9':
    xp-needed: 50000000
  '10':
    xp-needed: 100000000