# Level data yaml
#level_name:
#  title: "&dCool Level" # The title is what the players will see for the level
#  message: "&1You've completed &5%title%&d!" # Message sent to player after level completion(if unset, the default will be used); Default is unset
#  max_completions: 2 # How many completions are allowed for the level(If unset there are unlimited completions); Default is unset
#  broadcast_completion: True # False by default, does not need to be set