# Reward data yaml

example_perk:
  title: "&a&lExample Perk"
  permissions:
    - example.permission
  requirements:
    - coal-1
    - coal-2
  price: 10

nothingness:
  title: "&7Nothingness Perk"
  permissions:
    - example.permission
  requirements: []

diamond:
  title: "&bNotorious Diamond Perk"
  permissions:
    - example.permission
  requirements:
    - diamond-1
    - diamond-2
    - diamond-3
  price: 100000
