# Settings yaml

database:
  host: ""
  port:
  database: "parkourcraft_parkour_stats_new"
  username: ""
  password: ""

levels:
  message:
    completion: "&7Rewarded &6%reward% &7coins for beating %title% &2(&a#%completions%&2)"
    broadcast: "&a%player% &7has beaten %title%"

# It will check if that line contains 'Click Here', or whatever is defined
signs:
  first_line: "Click Here"
  second_line:
    completion: "To redeem"
    spawn: "To return to"
