# Settings yaml

database:
  host: ""
  port:
  database: "parkourcraft_parkour_stats_new"
  username: ""
  password: ""

levels:
  message:
    completion: "&7Rewarded &6%reward% Coins &7for beating %title% &7in &a%time% &2(&a#%completions%&2)"
    broadcast: "&a%player% &7has beaten %title%"
  featured_level_reward_multiplier: 1.50

# It will check if that line contains 'Click Here', or whatever is defined
signs:
  first_line: "Click Here"
  second_line:
    completion: "To redeem"
    spawn: "To return to"

setup-sword:
  type: IRON_SWORD
  title: "&cSetup Sword"
  hotbar_slot: 1

clans:
  max_members: 5
  split_reward_min_needed: 300
  price:
    create: 10000
    tag: 1000
  tag_length:
    min: 4
    max: 6
  clan_xp_calc:
    level-reward-needed: 100
    min-percent: 10
    max-percent: 25
player_submitted:
  world: ""
  plot_width: 75
  plot_default_y: 64
  plot_buffer_width: 10
  minimum_rank_for_plot_creation: "novice-i"
event:
  reminder_delay: 300
  max_run_time: 1800
  check_next_event_delay: 7200
  min_players_online: 5
  anvil_spawn_percentage: 0.9
  anvil_spawn_y_above_start_y: 40
  task_delay:
    pvp: 5
    half_heart: 15
    rising_water: 100
infinitepk:
  max_leaderboard_size: 10
  max_x: 100
  max_y: 200
  max_z: 100
  starting_y: 150
completions:
  global_level_completions_leaderboard:
    max_size: 10
  global_personal_completions_leaderboard:
    max_size: 10
prestiges:
  max_multiplier: 1.25
  multiplier_per_prestige: 0.05