# Settings yaml

database:
  host: ""
  port:
  database: ""
  username: ""
  password: ""

main_world: "parkour"
bank:
  radiant:
    min_starting_bid: 100
  brilliant:
    min_starting_bid: 1000
  legendary:
    min_starting_bid: 3000
  jackpot:
    length: 1800 # in seconds
minimum_pay_amount: 10.0
blackmarket:
  reset_time:
    day: sunday
    hour: 15
gg:
  default_timer_in_seconds: 10
  default_coin_reward: 10
levels:
  message:
    completion: "&7Rewarded &6%reward% Coins &7for %title% &7in &a%time% &2(&a%completions%&2)"
    broadcast: "&a%player% &7has beaten %title%"
  featured_level_reward_multiplier: 1.50
  max_rated_levels_leaderboard_size: 10
  tutorial_level: tutorial
cooldowns:
  reset_time: "3:15"
  modifiers:
    '3':
      modifier: 0.25
    '5':
      modifier: 0.50
    '7':
      modifier: 0.75
    '9':
      modifier: 0.90
stats:
  max_coins_leaderboard_size: 10

records:
  max_leaderboard_size: 10

join_inventory:
  '0':
    item:
      material: SKULL_ITEM
      type: 3
      title: "&aYour Profile"
      lore:
        - '&7Click me to view your own profile'
  '4':
    item:
      material: PRISMARINE_CRYSTALS
      title: '&b&lParkour &7Levels'
      lore:
        - '&7Right click to open up'
        - ' &7the &bParkour &7Levels menu'
  '8':
    item:
      material: REDSTONE_TORCH_ON
      title: '&2Players &7» &2Enabled'
  '5':
    item:
      material: GOLD_PLATE
      title: '&eLast Checkpoint'
      lore:
        - '&7Right click to teleport'
        - ' &7to your last checkpoint'
  '3':
    item:
      material: WOOD_DOOR
      title: '&cReset'
      lore:
        - '&7Right click to reset'
        - ' &7your current level progress'
ascendance:
  realm_world: "ascendant_realm"
  hub_level: "ascendantrealm"
# It will check if that line contains 'Click Here', or whatever is defined
signs:
  first_line: "Click Here"
  second_line:
    completion: "To redeem"
    spawn: "To return to"
setup-sword:
  prestiges:
    '0':
      type: WOOD_SWORD
      enchanted: false
    '1':
      type: STONE_SWORD
      enchanted: false
    '2':
      type: IRON_SWORD
      enchanted: false
    '3':
      type: GOLD_SWORD
      enchanted: false
    '4':
      type: DIAMOND_SWORD
      enchanted: false
    '5':
      type: WOOD_SWORD
      glow: true
    '6':
      type: STONE_SWORD
      glow: true
    '7':
      type: IRON_SWORD
      glow: true
    '8':
      type: GOLD_SWORD
      glow: true
    '9':
      type: DIAMOND_SWORD
      glow: true
  title: "&cSetup Sword"
  hotbar_slot: 1
practice-plate:
  type: IRON_PLATE
  title: "&6Practice Checkpoint"
  hotbar_slot: 2
clans:
  max_members: 5
  split_reward_min_needed: 300
  max_leaderboard_size: 10
  price:
    create: 10000
    tag: 1000
  tag_length:
    min: 4
    max: 6
  clan_xp_calc:
    level-reward-needed: 100
    min-percent: 10
    max-percent: 25
  blocked_clan_names:
    - "nigger"
    - "nigga"
    - "nigg"
    - "ni99a"
    - "ni99er"
    - "n!99er"
    - "n!99a"
    - "retard"
    - "retarded"
    - "fag"
    - "faggot"
    - "fagg0t"
    - "coon"
    - "nibba"
    - "beaner"
    - "nazi"
    - "hitler"
    - "n1gger"
    - "nigg"
    - "chink"
player_submitted:
  world: ""
  plot_width: 75
  plot_default_y: 64
  plot_buffer_width: 10
  minimum_rank_for_plot_creation: "novice-i"
event:
  reminder_delay: 300
  max_run_time: 1800
  check_next_event_delay: 7200
  min_players_online: 5
  anvil_spawn_percentage: 0.9
  anvil_spawn_y_above_start_y: 40
  task_delay:
    pvp: 5
    half_heart: 15
    rising_water: 100
infinitepk:
  max_leaderboard_size: 10
  max_x: 100
  max_y: 240
  min_y: 200
  max_z: 100
  starting_y: 220
  starting_pitch: 0.0f
  starting_yaw: 0.0f
  portal_respawn:
completions:
  global_level_completions_leaderboard:
    max_size: 10
  global_personal_completions_leaderboard:
    max_size: 10
prestiges:
  max_multiplier: 30
  multiplier_per_prestige: 10
  base_prestige_cost: 1000000.0
  additional_cost_per_prestige: 1000000.0
races:
  max_leaderboard_size: 10
  min_bet_amount: 100.0
rage_quit:
  price: 10000.0
  messages:
    - "&6&l%player% &7slipped on a pickle and &c&lRage Quit"
    - "&6&l%player% &7lost a 1v1 with a cow and &c&lRage Quit"
    - "&6&l%player% &7slipped on kiot's apple and &c&lRage Quit"
    - "&6&l%player% &7lost chess in 2 turns and &c&lRage Quit"
    - "&6&l%player% &7found a pack of wolves and &c&lRage Quit"
    - "&6&l%player% &7failed at the last jump and &c&lRage Quit"
    - "&6&l%player% &7tripped and &c&lRage Quit"
    - "&6&l%player% &7fell on a spike and &c&lRage Quit"
    - "&6&l%player% &7drank too much BBQ sauce and &c&lRage Quit"
    - "&6&l%player% &7respectfully &c&l&oRage Quit"
    - "&6&l%player% &7bought &c/ragequit &7to &c&lRage Quit"
    - "&6&l%player% &7went for a swim in syrup and &c&lRage Quit"
    - "&6&l%player% &7failed their test and &c&lRage Quit"
    - "&6&l%player% &7missed their bedtime and &c&lRage Quit"
    - "&6&l%player% &7got the great idea to &c&lRage Quit"