# Settings yaml

database:
  host: ""
  port:
  database: "parkourcraft_parkour_stats_new"
  username: ""
  password: ""

levels:
  message:
    completion: "&7Rewarded &6%reward% Coins &7for beating %title% &7in &a%time% &2(&a#%completions%&2)"
    broadcast: "&a%player% &7has beaten %title%"

# It will check if that line contains 'Click Here', or whatever is defined
signs:
  first_line: "Click Here"
  second_line:
    completion: "To redeem"
    spawn: "To return to"

clans:
  max_members: 5
  split_reward_min_needed: 300
  price:
    create: 10000
    tag: 1000
  tag_length:
    min: 4
    max: 6
  clan_xp_calc:
    level-reward-needed: 100
    min-percent: 10
    max-percent: 25

spawn:
  location: