name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: [CrazySeanPC, xxBen]

depend: [TitleAPI, Vault, WorldGuard, ProtocolLib, WorldEdit]
softdepend: [PlaceholderAPI]

commands:
  level:
    description: "Momentum level management command"
    aliases: [lvl, levels]
  location:
    description: "Momentum location management command"
    aliases: [loc, locations]
  menu:
    description: "Momentum menu management command"
    aliases: [menus]
  perks:
    description: "Momentum perks management command"
    aliases: [perk]
  stats:
    description: "Momentum stats display command"
  spectate:
    description: "Momentum spectate command"
  clan:
    description: "Momentum clan management command"
    aliases: [clans]
  momentum:
    description: "Momentum main command"
  toggleplayers:
    description: "Momentum player toggling command"
  checkpoint:
    description: "Momentum checkpoint command"
  setspawn:
    description: "Momentum setspawn command"
  spawn:
    description: "Momentum spawn command"
  practice:
    description: "Momentum practice command"
    aliases: [prac, unprac]
  race:
    description: "Momentum race command"
    aliases: [races]
  rank:
    description: "Momentum rank command"
    aliases: [ranks]
  rankup:
    description: "Momentum rankup command"
  plot:
    description: "Momentum player submitted command"
    aliases: [plots, playersubmitted, playersubmit]
  event:
    description: "Momentum events command"
  prestige:
    description: "Momentum prestige command"
  rate:
    description: "Momentum rate command"
    aliases: [ratelevel, levelrate]
  sword:
    description: "Momentum sword command"
    aliases: [setup, setupsword]
  infinite:
    description: "Momentum InfinitePK command"
    aliases: [infinitepk, endless, endlesspk]
  profile:
    description: "Momentum profile command"
    aliases: [profilestats]
  cosmetics:
    description: "Momentum cosmetics command"
    aliases: [shop]
  ragequit:
    description: "Momentum rage quit command"
    aliases: [rq, rage]
  nightvision:
    description: "Momentum night vision command"
    aliases: [nv, nightvision]
  practicego:
    description: "Momentum practice go command"
    aliases: [pgo, ptp, practicetp, pracgo, practp]
  grinding:
    description: "Momentum grinding command"
    aliases: [togglegrind, grindmode, grind]
  coins:
    description: "Momentum coins command"
    aliases: [c, coin]
  records:
    description: "Momentum records command"
    aliases: [levelrecords]
  tutorial:
    description: "Momentum tutorial command"
  fails:
    description: "Momentum fails command"
    aliases: [fail]
  join:
    description: "Momentum join command"
  play:
    description: "Momentum play command"
  save:
    description: "Momentum save command"
    aliases: [saveloc, savelevel, savelocation, saves]
  pay:
    description: "Momentum pay command"
    aliases: [etransfer]