name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: CrazySeanPC

depend: [TitleAPI, Vault]

commands:
  level:
    description: "Level creation command"
    aliases: [lvl, levels]