name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: CrazySeanPC

depend: [TitleAPI, Vault, WorldGuard, MVdWPlaceholderAPI]

commands:
  level:
    description: "PC-Parkour level management"
    aliases: [lvl, levels]
  location:
    description: "PC-Parkour location management"
    aliases: [loc, locations]
  menu:
    description: "PC-Parkour menu management"
    aliases: [menus]
  rewards:
    description: "PC-Parkour rewards management"
    aliases: [reward]
  stats:
    description: "PC-Parkour stats display"