name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: CrazySeanPC

depend: [TitleAPI, Vault, WorldGuard]

commands:
  level:
    description: "Level creation command"
    aliases: [lvl, levels]
  location:
    description: "Locations management"
    aliases: [loc, locations]
  stats:
    description: "Display stats"