name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: [CrazySeanPC, xxBen]

depend: [TitleAPI, Vault, WorldGuard, EasyScoreboards, ProtocolLib, WorldEdit]

commands:
  level:
    description: "PC-Parkour level management"
    aliases: [lvl, levels]
  location:
    description: "PC-Parkour location management"
    aliases: [loc, locations]
  menu:
    description: "PC-Parkour menu management"
    aliases: [menus]
  perks:
    description: "PC-Parkour perks management"
    aliases: [perk]
  stats:
    description: "PC-Parkour stats display"
  setarmor:
    description: "PC-Parkour armor setting command"
  spectate:
    description: "Spectate another player"
  clan:
    description: "Clan management"
    aliases: [clans]
  pc-parkour:
    description: "Parkour"
  toggleplayers:
    description: "PC-Parkour Player Toggling Command"
  checkpoint:
    description: "PC-Parkour Checkpoint COmmand"
  setspawn:
    description: "PC-Parkour SetSpawn Command"
  spawn:
    description: "PC-Parkour Spawn Command"
  practice:
    description: "PC-Parkour Practice Command"
    aliases: [prac]
  race:
    description: "PC-Parkour Race Command"
    aliases: [races]
  rank:
    description: "PC-Parkour Rank Command"
    aliases: [ranks]
  rankup:
    description: "PC-Parkour Rankup Command"
  plot:
    description: "PC-Parkour Player Submitted Command"
    aliases: [plots, playersubmitted, playersubmit]
  event:
    description: "PC-Parkour Events Command"
  prestige:
    description: "PC-Parkour Prestige Command"
  rate:
    description: "PC-Parkour Rate Command"
    aliases: [ratelevel, levelrate]
  sword:
    description: "PC-Parkour Sword Command"
    aliases: [setup, setupsword]
  infinite:
    description: "PC-Parkour InfinitePK Command"
    aliases: [infinitepk, endless, endlesspk]
  profile:
    description: "PC-Parkour Profile Command"
    aliases: [profilestats]