name: ${project.name}
description: "${project.description}"
main: ${mainClass}
version: ${project.version}
author: [CrazySeanPC, xxBen]

depend: [TitleAPI, Vault, WorldGuard, ProtocolLib, WorldEdit]
softdepend: [PlaceholderAPI]

commands:
  level:
    description: "RN-Parkour level management command"
    aliases: [lvl, levels]
  location:
    description: "RN-Parkour location management command"
    aliases: [loc, locations]
  menu:
    description: "RN-Parkour menu management command"
    aliases: [menus]
  perks:
    description: "RN-Parkour perks management command"
    aliases: [perk]
  stats:
    description: "RN-Parkour stats display command"
  spectate:
    description: "RN-Parkour spectate command"
  clan:
    description: "RN-Parkour clan management command"
    aliases: [clans]
  rn-parkour:
    description: "RN-Parkour main command"
  toggleplayers:
    description: "RN-Parkour player toggling command"
  checkpoint:
    description: "RN-Parkour checkpoint command"
  setspawn:
    description: "RN-Parkour setspawn command"
  spawn:
    description: "RN-Parkour spawn command"
  practice:
    description: "RN-Parkour practice command"
    aliases: [prac, unprac]
  race:
    description: "RN-Parkour race command"
    aliases: [races]
  rank:
    description: "RN-Parkour rank command"
    aliases: [ranks]
  rankup:
    description: "RN-Parkour rankup command"
  plot:
    description: "RN-Parkour player submitted command"
    aliases: [plots, playersubmitted, playersubmit]
  event:
    description: "RN-Parkour events command"
  prestige:
    description: "RN-Parkour prestige command"
  rate:
    description: "RN-Parkour rate command"
    aliases: [ratelevel, levelrate]
  sword:
    description: "RN-Parkour sword command"
    aliases: [setup, setupsword]
  infinite:
    description: "RN-Parkour InfinitePK command"
    aliases: [infinitepk, endless, endlesspk]
  profile:
    description: "RN-Parkour profile command"
    aliases: [profilestats]
  cosmetics:
    description: "RN-Parkour cosmetics command"
    aliases: [shop]
  ragequit:
    description: "RN-Parkour rage quit command"
    aliases: [rq, rage]
  nightvision:
    description: "RN-Parkour night vision command"
    aliases: [nv, nightvision]
  practicego:
    description: "RN-Parkour practice go command"
    aliases: [pgo, ptp, practicetp, pracgo, practp]
  grinding:
    description: "RN-Parkour grinding command"
    aliases: [togglegrind, grindmode, grind]
  coins:
    description: "RN-Parkour coins command"
    aliases: [c, coin]
  records:
    description: "RN-Parkour records command"
    aliases: [levelrecords]
  tutorial:
    description: "RN-Parkour tutorial command"
  fails:
    description: "RN-Parkour fails command"
    aliases: [fail]
  join:
    description: "RN-Parkour join command"
  play:
    description: "RN-Parkour play command"
  save:
    description: "RN-Parkour save command"
    aliases: [saveloc, savelevel, savelocation, saves]
  jackpot:
    description: "RN-Parkour jackpot command"
    aliases: [jp, sponsor]
  pay:
    description: "RN-Parkour pay command"
    aliases: [etransfer]
  modifier:
    description: "RN-Parkour modifier command"
    aliases: [modifiers, booster, discount, boosters, discounts]